DO $postflight$ DECLARE fn text; tab text; role_name text; privilege_name text; BEGIN
 IF (SELECT data_snapshot FROM leader_private.leader_rollout_backups WHERE id='operational-commands-20261009-v1') IS DISTINCT FROM jsonb_build_object('leader_orders',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY id),'[]'::jsonb) FROM public.leader_orders t),'leader_production_jobs',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY id),'[]'::jsonb) FROM public.leader_production_jobs t),'leader_production_events',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY id),'[]'::jsonb) FROM public.leader_production_events t),'leader_installation_jobs',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY id),'[]'::jsonb) FROM public.leader_installation_jobs t),'leader_installation_job_items',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY id),'[]'::jsonb) FROM public.leader_installation_job_items t),'leader_installation_events',(SELECT coalesce(jsonb_agg(to_jsonb(t) ORDER BY id),'[]'::jsonb) FROM public.leader_installation_events t)) THEN RAISE EXCEPTION 'business_rows_changed'; END IF;
 FOREACH fn IN ARRAY ARRAY['leader_private.leader_installation_command_error(uuid,text,text)','leader_private.leader_installation_status_key(text)','leader_private.leader_installation_status_label(text)','leader_private.leader_installation_transition_allowed(text,text)','leader_private.leader_production_command_error(uuid,text,text)','leader_private.leader_production_is_installation_ready(text)','leader_private.leader_production_status_key(text)','leader_private.leader_production_status_label(text)','leader_private.leader_production_transition_allowed(text,text)','public.leader_create_installation_job_from_order_rpc(jsonb)','public.leader_create_production_job_from_order_impl_rpc(jsonb)','public.leader_create_production_job_from_order_rpc(jsonb)','public.leader_read_installation_job_rpc(uuid,uuid)','public.leader_update_installation_job_rpc(jsonb)','public.leader_update_production_job_rpc(jsonb)','leader_private.leader_layout_is_approved(text)'] LOOP
 IF has_function_privilege('anon',fn,'EXECUTE') OR has_function_privilege('authenticated',fn,'EXECUTE') OR NOT has_function_privilege('service_role',fn,'EXECUTE') THEN RAISE EXCEPTION 'unsafe_rpc_acl:%',fn; END IF;
 END LOOP;
 FOREACH tab IN ARRAY ARRAY['leader_production_jobs','leader_production_events','leader_installation_jobs','leader_installation_job_items','leader_installation_events'] LOOP
 FOREACH role_name IN ARRAY ARRAY['anon','authenticated'] LOOP
 FOREACH privilege_name IN ARRAY ARRAY['INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'] LOOP
 IF has_table_privilege(role_name,'public.'||tab,privilege_name) THEN RAISE EXCEPTION 'direct_write_open:%:%:%',tab,role_name,privilege_name; END IF;
 END LOOP;
 IF has_any_column_privilege(role_name,'public.'||tab,'UPDATE') OR has_any_column_privilege(role_name,'public.'||tab,'INSERT') THEN RAISE EXCEPTION 'column_write_open'; END IF;
 END LOOP;
 END LOOP;
 IF has_column_privilege('authenticated','public.leader_production_jobs','contractor_cost','SELECT') OR has_column_privilege('authenticated','public.leader_installation_jobs','client_phone','SELECT') OR has_column_privilege('authenticated','public.leader_installation_jobs','installer_cost','SELECT') THEN RAISE EXCEPTION 'private_read_open'; END IF;
END $postflight$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_installation_command_error(uuid,text,text)'::regprocedure)) <> 'd263ee000b817642f549016be44d80de' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_installation_command_error'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_installation_status_key(text)'::regprocedure)) <> '12243bd5d50a49a8bf7e281d715bba03' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_installation_status_key'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_installation_status_label(text)'::regprocedure)) <> '3a1082636d166768f2b3334d76e1743d' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_installation_status_label'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_installation_transition_allowed(text,text)'::regprocedure)) <> '2463ec1b87fa4cf46a04590ac7e97d60' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_installation_transition_allowed'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_production_command_error(uuid,text,text)'::regprocedure)) <> '775cab4f89b0bb4d55653ed50b5fc50a' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_production_command_error'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_production_is_installation_ready(text)'::regprocedure)) <> '10efb8a0883f7b139a0c0ad85fe7bfda' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_production_is_installation_ready'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_production_status_key(text)'::regprocedure)) <> '803405dcbc204a060b8a9df569a55f8d' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_production_status_key'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_production_status_label(text)'::regprocedure)) <> '4a5a5674c42eb4c403c33c718178a2e7' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_production_status_label'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('leader_private.leader_production_transition_allowed(text,text)'::regprocedure)) <> '6bffa45e4fec6fd0cf937da9bd2c6a99' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_production_transition_allowed'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('public.leader_create_installation_job_from_order_rpc(jsonb)'::regprocedure)) <> 'c81c3932092b5e2a2c63e0df38568ff0' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_create_installation_job_from_order_rpc'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('public.leader_create_production_job_from_order_impl_rpc(jsonb)'::regprocedure)) <> '5ae61afa84c0117edfd78f33e9a3d302' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_create_production_job_from_order_impl_rpc'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('public.leader_create_production_job_from_order_rpc(jsonb)'::regprocedure)) <> '545bd184195160db5c6d182d92490d3b' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_create_production_job_from_order_rpc'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('public.leader_read_installation_job_rpc(uuid,uuid)'::regprocedure)) <> '5a353818606012d0e657a83f133723b6' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_read_installation_job_rpc'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('public.leader_update_installation_job_rpc(jsonb)'::regprocedure)) <> '72be911e2160249b5db08cec8b686982' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_update_installation_job_rpc'; END IF;END $$;
DO $$BEGIN IF md5(pg_get_functiondef('public.leader_update_production_job_rpc(jsonb)'::regprocedure)) <> '14f07030acf8775c15aace2308199c62' THEN RAISE EXCEPTION 'runtime_fingerprint:leader_update_production_job_rpc'; END IF;END $$;
