-- LOCAL CI RECONSTRUCTION ONLY.
-- Reconstructs the final state of the three hosted staging migrations from 2026-07-18:
--   20260718100759 offer_create_from_calculation_install
--   20260718100935 offer_create_from_calculation_fk_index
--   20260718101751 offer_create_from_calculation_input_lock_hardening
-- The original migration source is absent from the current Git tree.
-- Table/index metadata and the RPC were read from lider-bsk-staging on 2026-10-01.
-- The RPC below is deliberately reversed to its pre-2026-09-07 privacy form so the
-- committed 20260907_01_offer_client_privacy_default.sql migration can replay normally.
-- NEVER apply this file to production or the hosted staging project.

do $guard$
begin
  if not exists (
    select 1 from leader_staging.environment_guard
    where singleton = true
      and project_ref = 'otulfnouybahfnsycxqn'
      and environment_name = 'staging'
      and repository = 'deputat36/lider-bsk'
  ) then
    raise exception 'staging_environment_guard_failed';
  end if;
end
$guard$;

create table if not exists public.leader_commercial_offers (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leader_leads(id) on delete cascade,
  calculation_id uuid references public.leader_lead_calculations(id) on delete set null,
  client_id uuid,
  order_id uuid references public.leader_orders(id) on delete set null,
  offer_number bigint generated by default as identity
    (start with 1001 increment by 1 minvalue 1 no cycle) not null,
  offer_type text not null default 'Короткое',
  title text not null default 'Коммерческое предложение',
  short_text text,
  full_text text,
  total_sum numeric not null default 0 check (total_sum > 0),
  valid_until date,
  status text not null default 'Черновик',
  sent_at timestamptz,
  approved_at timestamptz,
  rejected_at timestamptz,
  created_by uuid,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.leader_commercial_offer_events (
  id uuid primary key default gen_random_uuid(),
  offer_id uuid not null references public.leader_commercial_offers(id) on delete cascade,
  lead_id uuid references public.leader_leads(id) on delete cascade,
  calculation_id uuid references public.leader_lead_calculations(id) on delete set null,
  event_type text not null default 'Комментарий',
  old_status text,
  new_status text,
  comment text,
  created_by uuid,
  created_by_email text,
  created_at timestamptz not null default now()
);

create unique index if not exists leader_commercial_offers_calculation_uidx
  on public.leader_commercial_offers(calculation_id)
  where calculation_id is not null;
create index if not exists leader_commercial_offers_lead_created_idx
  on public.leader_commercial_offers(lead_id, created_at desc);
create index if not exists leader_commercial_offers_order_id_idx
  on public.leader_commercial_offers(order_id);
create index if not exists leader_commercial_offer_events_calculation_id_idx
  on public.leader_commercial_offer_events(calculation_id);
create index if not exists leader_commercial_offer_events_lead_id_idx
  on public.leader_commercial_offer_events(lead_id);
create index if not exists leader_commercial_offer_events_offer_created_idx
  on public.leader_commercial_offer_events(offer_id, created_at);

alter table public.leader_commercial_offers enable row level security;
alter table public.leader_commercial_offer_events enable row level security;

revoke all on table public.leader_commercial_offers from public, anon, authenticated;
revoke all on table public.leader_commercial_offer_events from public, anon, authenticated;
grant select, insert, update on table public.leader_commercial_offers to service_role;
grant select, insert on table public.leader_commercial_offer_events to service_role;
grant usage on sequence public.leader_commercial_offers_offer_number_seq to service_role;

CREATE OR REPLACE FUNCTION leader_private.leader_create_offer_from_calculation_rpc_internal_v1(p_payload jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_actor_id uuid;
  v_request jsonb;
  v_request_id uuid;
  v_expected_updated_at timestamptz;
  v_payload jsonb;
  v_normalized_payload jsonb;
  v_action text;
  v_calculation_id uuid;
  v_idempotency_key text;
  v_title text;
  v_valid_until date;
  v_extra_comment text;
  v_profile public.leader_user_profiles%rowtype;
  v_calculation public.leader_lead_calculations%rowtype;
  v_item public.leader_lead_calculation_items%rowtype;
  v_lead public.leader_leads%rowtype;
  v_need public.leader_lead_needs%rowtype;
  v_offer public.leader_commercial_offers%rowtype;
  v_event public.leader_commercial_offer_events%rowtype;
  v_receipt leader_private.leader_command_receipts%rowtype;
  v_existing_receipt leader_private.leader_command_receipts%rowtype;
  v_request_hash text;
  v_canonical jsonb;
  v_response jsonb;
  v_lead_json jsonb;
  v_need_json jsonb := '{}'::jsonb;
  v_calculation_json jsonb;
  v_lead_name text;
  v_lead_phone text;
  v_lead_service text;
  v_need_text text;
  v_short_items text := '';
  v_full_items text := '';
  v_short_text text;
  v_full_text text;
  v_public_total numeric := 0;
  v_item_count integer := 0;
  v_money text;
  v_qty text;
  v_now timestamptz;
  v_constraint_name text;
  v_exception_state text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    return jsonb_build_object('ok', false, 'request_id', null,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'RPC payload must be an object'));
  end if;

  if exists (
    select 1 from jsonb_object_keys(p_payload) as k(key)
    where key not in ('actor_id', 'actor_email', 'request')
  ) then
    return jsonb_build_object('ok', false, 'request_id', null,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'Unknown RPC payload field'));
  end if;

  begin
    v_actor_id := nullif(btrim(p_payload ->> 'actor_id'), '')::uuid;
  exception when others then
    return jsonb_build_object('ok', false, 'request_id', null,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'actor_id must be UUID'));
  end;

  v_request := p_payload -> 'request';
  if v_actor_id is null or v_request is null or jsonb_typeof(v_request) <> 'object' then
    return jsonb_build_object('ok', false, 'request_id', null,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'actor_id and request are required'));
  end if;

  if exists (
    select 1 from jsonb_object_keys(v_request) as k(key)
    where key not in ('action', 'request_id', 'expected_updated_at', 'payload')
  ) then
    return jsonb_build_object('ok', false, 'request_id', null,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'Unknown request field'));
  end if;

  v_action := btrim(v_request ->> 'action');
  if v_action <> 'offer.create_from_calculation' then
    return jsonb_build_object('ok', false, 'request_id', v_request ->> 'request_id',
      'error', jsonb_build_object('code', 'unknown_action', 'message', 'Unsupported action'));
  end if;

  begin
    v_request_id := nullif(btrim(v_request ->> 'request_id'), '')::uuid;
    v_expected_updated_at := nullif(btrim(v_request ->> 'expected_updated_at'), '')::timestamptz;
  exception when others then
    return jsonb_build_object('ok', false, 'request_id', v_request ->> 'request_id',
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'request_id or expected_updated_at is invalid'));
  end;

  v_payload := v_request -> 'payload';
  if v_request_id is null or v_expected_updated_at is null
     or v_payload is null or jsonb_typeof(v_payload) <> 'object' then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'Request fields are required'));
  end if;

  if exists (
    select 1 from jsonb_object_keys(v_payload) as k(key)
    where key not in ('calculation_id', 'idempotency_key', 'title', 'valid_until', 'extra_comment')
  ) then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'Unknown or server-owned business field'));
  end if;

  if jsonb_typeof(v_request -> 'action') <> 'string'
     or jsonb_typeof(v_request -> 'request_id') <> 'string'
     or jsonb_typeof(v_request -> 'expected_updated_at') <> 'string'
     or jsonb_typeof(v_payload -> 'calculation_id') <> 'string'
     or jsonb_typeof(v_payload -> 'idempotency_key') <> 'string'
     or jsonb_typeof(v_payload -> 'title') <> 'string'
     or jsonb_typeof(v_payload -> 'valid_until') <> 'string'
     or (
       v_payload ? 'extra_comment'
       and jsonb_typeof(v_payload -> 'extra_comment') not in ('string', 'null')
     ) then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'Request field types are invalid'));
  end if;

  if (v_payload ->> 'valid_until') !~ '^\d{4}-\d{2}-\d{2}$' then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'valid_until must be YYYY-MM-DD'));
  end if;

  begin
    v_calculation_id := nullif(btrim(v_payload ->> 'calculation_id'), '')::uuid;
    v_valid_until := nullif(btrim(v_payload ->> 'valid_until'), '')::date;
  exception when others then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'calculation_id or valid_until is invalid'));
  end;

  v_idempotency_key := btrim(v_payload ->> 'idempotency_key');
  v_title := btrim(v_payload ->> 'title');
  v_extra_comment := nullif(btrim(v_payload ->> 'extra_comment'), '');

  if v_calculation_id is null
     or v_idempotency_key is null or char_length(v_idempotency_key) not between 1 and 160
     or v_title is null or char_length(v_title) not between 1 and 500
     or char_length(coalesce(v_extra_comment, '')) > 4000 then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_payload', 'message', 'Business payload is invalid'));
  end if;

  if v_valid_until is null or v_valid_until < current_date or v_valid_until > current_date + 730 then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_valid_until', 'message', 'valid_until must be within the next 730 days'));
  end if;

  select * into v_profile
  from public.leader_user_profiles
  where user_id = v_actor_id and is_active = true
  for share;

  if not found then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'inactive_profile', 'message', 'Active profile is required'));
  end if;

  if lower(btrim(v_profile.role)) not in ('owner', 'admin', 'manager') then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'forbidden', 'message', 'offers.write is required'));
  end if;

  v_normalized_payload := jsonb_build_object(
    'calculation_id', v_calculation_id,
    'idempotency_key', v_idempotency_key,
    'title', v_title,
    'valid_until', to_char(v_valid_until, 'YYYY-MM-DD'),
    'extra_comment', v_extra_comment
  );
  v_canonical := jsonb_build_object(
    'action', v_action,
    'expected_updated_at', to_char(v_expected_updated_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
    'payload', v_normalized_payload,
    'actor_id', v_actor_id
  );
  v_request_hash := encode(extensions.digest(convert_to(v_canonical::text, 'UTF8'), 'sha256'), 'hex');

  perform pg_advisory_xact_lock(hashtextextended(v_action || ':receipt:' || v_idempotency_key, 0));

  select * into v_existing_receipt
  from leader_private.leader_command_receipts
  where action = v_action and idempotency_key = v_idempotency_key
  for update;

  if found then
    if v_existing_receipt.request_hash <> v_request_hash then
      return jsonb_build_object('ok', false, 'request_id', v_request_id,
        'error', jsonb_build_object('code', 'idempotency_conflict', 'message', 'Idempotency key was used with another payload'));
    end if;
    if v_existing_receipt.state = 'success' and v_existing_receipt.response is not null then
      return v_existing_receipt.response || jsonb_build_object('idempotent_replay', true);
    end if;
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'idempotency_conflict', 'message', 'Command is already in progress'));
  end if;

  if exists (
    select 1 from leader_private.leader_command_receipts
    where action = v_action and request_id = v_request_id
  ) then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'request_id_conflict', 'message', 'request_id was already used'));
  end if;

  select * into v_calculation
  from public.leader_lead_calculations
  where id = v_calculation_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'calculation_not_found', 'message', 'Calculation was not found'));
  end if;

  if v_calculation.updated_at is distinct from v_expected_updated_at then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'calculation_changed', 'message', 'Calculation changed; reload before creating an offer'));
  end if;

  v_calculation_json := to_jsonb(v_calculation);
  if v_calculation_json ? 'is_current_revision'
     and coalesce((v_calculation_json ->> 'is_current_revision')::boolean, false) is not true then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'calculation_not_current', 'message', 'Offer can only be created from the current calculation revision'));
  end if;

  if v_calculation.commercial_offer_id is not null or exists (
    select 1 from public.leader_commercial_offers where calculation_id = v_calculation.id
  ) then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'offer_already_exists', 'message', 'An offer already exists for this calculation'));
  end if;

  if v_calculation.client_total <= 0 then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_calculation', 'message', 'Calculation client total must be positive'));
  end if;

  select * into v_lead
  from public.leader_leads
  where id = v_calculation.lead_id
  for update;

  if not found then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_calculation', 'message', 'Calculation lead was not found'));
  end if;

  if v_calculation.need_id is not null then
    select * into v_need
    from public.leader_lead_needs
    where id = v_calculation.need_id and lead_id = v_calculation.lead_id
    for share;
    if found then v_need_json := to_jsonb(v_need); end if;
  end if;

  for v_item in
    select *
    from public.leader_lead_calculation_items
    where calculation_id = v_calculation.id and client_sum > 0
    order by sort_order, created_at, id
    for share
  loop
    v_item_count := v_item_count + 1;
    v_public_total := v_public_total + v_item.client_sum;
    v_money := trim(to_char(round(v_item.client_sum, 2), 'FM999999999990.00')) || ' ₽';
    v_qty := trim(to_char(v_item.qty, 'FM999999999990.###'));
    v_short_items := v_short_items || E'\n— ' || v_item.name;
    v_full_items := v_full_items || E'\n— ' || v_item.name
      || ' — ' || v_qty || case when nullif(btrim(coalesce(v_item.unit, '')), '') is null then '' else ' ' || btrim(v_item.unit) end
      || ' — ' || v_money;
  end loop;

  v_public_total := round(v_public_total, 2);
  if v_item_count = 0 or v_public_total <= 0
     or abs(v_public_total - round(v_calculation.client_total, 2)) > 0.01 then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_calculation', 'message', 'Calculation items and client total are inconsistent'));
  end if;

  v_lead_json := to_jsonb(v_lead);
  v_lead_name := nullif(btrim(v_lead_json ->> 'name'), '');
  v_lead_phone := nullif(btrim(v_lead_json ->> 'phone'), '');
  v_lead_service := nullif(btrim(v_lead_json ->> 'service'), '');
  v_need_text := coalesce(
    nullif(btrim(v_need_json ->> 'description'), ''),
    nullif(btrim(v_need_json ->> 'title'), ''),
    nullif(btrim(v_calculation.title), ''),
    v_lead_service,
    'Работы по заявке'
  );
  v_money := trim(to_char(round(v_calculation.client_total, 2), 'FM999999999990.00')) || ' ₽';

  v_short_text := 'Здравствуйте' || case when v_lead_name is null then '!' else ', ' || v_lead_name || '!' end
    || E'\n\nПодготовили расчёт по вашей заявке.'
    || E'\n\n' || coalesce(nullif(btrim(v_calculation.title), ''), 'Работы по заявке') || ' — ' || v_money || '.'
    || E'\n\nВ стоимость входит:' || v_short_items
    || E'\n\nСрок выполнения уточняется после согласования макета и предоплаты.'
    || E'\nДля запуска нужно подтвердить заказ и внести предоплату.'
    || case when v_extra_comment is null then '' else E'\n\n' || v_extra_comment end;

  v_full_text := 'КОММЕРЧЕСКОЕ ПРЕДЛОЖЕНИЕ'
    || E'\nРА «Лидер»'
    || E'\nДата: ' || to_char(current_date, 'DD.MM.YYYY')
    || E'\n\nКлиент: ' || coalesce(v_lead_name, 'не указано')
    || case when v_lead_phone is null then '' else E'\nТелефон: ' || v_lead_phone end
    || E'\n\nЗадача клиента\n' || v_need_text
    || E'\n\nСостав предложения' || v_full_items
    || E'\n\nИтоговая стоимость: ' || v_money
    || E'\n\nУсловия запуска'
    || E'\n1. Подтвердить состав работ и стоимость.'
    || E'\n2. Внести предоплату.'
    || E'\n3. Передать материалы или согласовать разработку дизайна.'
    || E'\n4. Согласовать финальный макет перед производством.'
    || case when nullif(btrim(coalesce(v_calculation.public_comment, '')), '') is null
      then '' else E'\n\nПримечание: ' || btrim(v_calculation.public_comment) end
    || case when v_extra_comment is null then '' else E'\n\nДополнительные условия: ' || v_extra_comment end
    || E'\n\nСрок действия предложения: до ' || to_char(v_valid_until, 'DD.MM.YYYY') || '.'
    || E'\nСрок выполнения зависит от согласования макета, наличия материалов и загрузки производства.';

  if char_length(v_short_text) > 8000 or char_length(v_full_text) > 50000 then
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'invalid_calculation', 'message', 'Generated offer text exceeds safe limits'));
  end if;

  v_now := clock_timestamp();

  insert into leader_private.leader_command_receipts (
    action, idempotency_key, request_id, request_hash, actor_id, state
  ) values (
    v_action, v_idempotency_key, v_request_id, v_request_hash, v_actor_id, 'in_progress'
  ) returning * into v_receipt;

  insert into public.leader_commercial_offers (
    lead_id, calculation_id, client_id, order_id, offer_type, title,
    short_text, full_text, total_sum, valid_until, status,
    created_by, updated_by, created_at, updated_at
  ) values (
    v_calculation.lead_id, v_calculation.id, v_calculation.client_id, v_calculation.order_id,
    'Подробное + короткое', v_title, v_short_text, v_full_text,
    v_calculation.client_total, v_valid_until, 'Черновик',
    v_actor_id, v_actor_id, v_now, v_now
  ) returning * into v_offer;

  update public.leader_lead_calculations
  set commercial_offer_id = v_offer.id,
      status = 'КП сформировано',
      updated_by = v_actor_id,
      updated_at = v_now
  where id = v_calculation.id
  returning * into v_calculation;

  update public.leader_leads
  set status = 'Расчёт подготовлен',
      updated_at = v_now
  where id = v_calculation.lead_id
  returning * into v_lead;

  insert into public.leader_commercial_offer_events (
    offer_id, lead_id, calculation_id, event_type, old_status, new_status,
    comment, created_by, created_by_email, created_at
  ) values (
    v_offer.id, v_offer.lead_id, v_offer.calculation_id,
    'offer.created_from_calculation', null, 'Черновик',
    'КП сформировано из сохранённого расчёта',
    v_actor_id, nullif(btrim(v_profile.email), ''), v_now
  ) returning * into v_event;

  v_response := jsonb_build_object(
    'ok', true,
    'request_id', v_request_id,
    'entity', jsonb_build_object(
      'id', v_offer.id,
      'lead_id', v_offer.lead_id,
      'calculation_id', v_offer.calculation_id,
      'client_id', v_offer.client_id,
      'order_id', v_offer.order_id,
      'offer_number', v_offer.offer_number,
      'offer_type', v_offer.offer_type,
      'title', v_offer.title,
      'short_text', v_offer.short_text,
      'full_text', v_offer.full_text,
      'total_sum', v_offer.total_sum,
      'valid_until', v_offer.valid_until,
      'status', v_offer.status,
      'sent_at', v_offer.sent_at,
      'approved_at', v_offer.approved_at,
      'rejected_at', v_offer.rejected_at,
      'created_at', v_offer.created_at,
      'updated_at', v_offer.updated_at
    ),
    'calculation', jsonb_build_object(
      'id', v_calculation.id,
      'lead_id', v_calculation.lead_id,
      'status', v_calculation.status,
      'commercial_offer_id', v_calculation.commercial_offer_id,
      'client_total', v_calculation.client_total,
      'updated_at', v_calculation.updated_at
    ),
    'lead', jsonb_build_object(
      'id', v_lead.id,
      'status', v_lead.status,
      'updated_at', v_lead.updated_at
    ),
    'events', jsonb_build_array(jsonb_build_object(
      'id', v_event.id,
      'offer_id', v_event.offer_id,
      'lead_id', v_event.lead_id,
      'calculation_id', v_event.calculation_id,
      'event_type', v_event.event_type,
      'old_status', v_event.old_status,
      'new_status', v_event.new_status,
      'comment', v_event.comment,
      'created_at', v_event.created_at
    )),
    'idempotent_replay', false
  );

  update leader_private.leader_command_receipts
  set state = 'success', response = v_response, updated_at = v_now, completed_at = v_now
  where id = v_receipt.id;

  return v_response;
exception
  when unique_violation then
    get stacked diagnostics v_constraint_name = constraint_name;
    if v_constraint_name = 'leader_command_receipts_action_request_id_key'
       or v_constraint_name = 'leader_command_receipts_action_request_uidx' then
      return jsonb_build_object('ok', false, 'request_id', v_request_id,
        'error', jsonb_build_object('code', 'request_id_conflict', 'message', 'request_id was already used'));
    end if;
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'offer_already_exists', 'message', 'An offer already exists for this calculation'));
  when others then
    get stacked diagnostics v_exception_state = returned_sqlstate;
    raise log 'leader_create_offer_from_calculation_rpc_internal_v1 failed request_id=% sqlstate=%',
      v_request_id, v_exception_state;
    return jsonb_build_object('ok', false, 'request_id', v_request_id,
      'error', jsonb_build_object('code', 'offer_create_failed', 'message', 'Commercial offer could not be persisted'));
end
$function$;


revoke all on function leader_private.leader_create_offer_from_calculation_rpc_internal_v1(jsonb)
  from public, anon, authenticated;
grant execute on function leader_private.leader_create_offer_from_calculation_rpc_internal_v1(jsonb)
  to service_role;

create or replace function public.leader_create_offer_from_calculation_rpc(p_payload jsonb)
returns jsonb
language sql
security invoker
set search_path = ''
as $function$
  select leader_private.leader_create_offer_from_calculation_rpc_internal_v1(p_payload);
$function$;

revoke all on function public.leader_create_offer_from_calculation_rpc(jsonb)
  from public, anon, authenticated;
grant execute on function public.leader_create_offer_from_calculation_rpc(jsonb)
  to service_role;
