import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),out=path.join(root,'artifacts/design-approval');
const mock=`
const order={id:'11111111-1111-4111-8111-111111111111',lead_id:'22222222-2222-4222-8222-222222222222',order_number:1,project_name:'Вывеска',status:'Макет на согласовании',layout_status:'На согласовании',updated_at:'2026-10-03T08:00:00.123456Z'};
const task={id:'33333333-3333-4333-8333-333333333333',order_id:order.id,task_status:'На согласовании',layout_status:'На согласовании',layout_link:null,updated_at:order.updated_at};
globalThis.mock={order,task,requests:[],fail:false};
export const supabaseClient={functions:{invoke:async(name,{body})=>{mock.requests.push(body);await new Promise(r=>setTimeout(r,100));if(mock.fail)return{data:{ok:false,error:{code:'conflict'}}};task.task_status=body.payload.status;task.layout_link=body.payload.layout_link;return{data:{ok:true,task:{...task}}}}},from(table){return{select(){return this},eq(){return this},order(){return this},single(){return this},async then(resolve){return resolve({data:table==='leader_orders'?{...order}:table==='leader_design_tasks'?[{...task}]:[],error:null})}}}};
`;
const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Согласование макета</title><style>body{font:16px Arial;margin:0}button{min-height:44px;font:inherit}*:focus-visible{outline:3px solid #b51721}</style></head><body><main><h1>Заказы</h1><button id="open" data-design-task-draft-order="11111111-1111-4111-8111-111111111111">Дизайн-задача</button></main><script type="module">import{v4State}from'/crm/v4/assets/v4/state.js';v4State.user={id:'actor-1'};v4State.profileLoaded=true;v4State.profile={role:'designer',is_active:true};await import('/crm/v4/assets/v4/design-task-draft-preview-v1.js');globalThis.ready=true;</script></body></html>`;
const server=createServer(async(req,res)=>{const p=new URL(req.url,'http://localhost').pathname;res.setHeader('Content-Type','text/javascript');if(p==='/test'){res.setHeader('Content-Type','text/html');return res.end(html)}if(p.endsWith('/supabase-client.js'))return res.end(mock);if(p.endsWith('/config.js'))return res.end("export const V4_CONFIG={supabaseUrl:'https://otulfnouybahfnsycxqn.supabase.co'}");try{const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw 0;res.end(await readFile(f))}catch{res.statusCode=404;res.end('missing')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});const results=[];
try{await mkdir(out,{recursive:true});for(const width of [360,390,768,1024,1440]){const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.waitForFunction(()=>globalThis.ready);await page.click('#open');const approve=page.locator('[data-design-task-transition="Согласовано"]');await approve.click();await page.waitForSelector('#designApprovalError:not([hidden])');assert.equal(await page.evaluate(()=>mock.requests.length),0);await page.fill('#designLayoutLink','javascript:alert(1)');await approve.click();assert.equal(await page.evaluate(()=>mock.requests.length),0);await page.fill('#designLayoutLink','https://files.example.org/layout.pdf');await approve.click();assert.equal(await page.evaluate(()=>mock.requests.length),0);if(width===360)await page.screenshot({path:path.join(out,'design-360.png'),fullPage:true});await page.check('#designApprovalConfirmed');await page.evaluate(()=>mock.fail=true);await approve.click();await page.waitForFunction(()=>mock.requests.length===1&&!document.querySelector('[data-design-task-transition]').disabled);assert.equal(await page.inputValue('#designLayoutLink'),'https://files.example.org/layout.pdf');await page.evaluate(()=>mock.fail=false);await approve.click();await page.waitForFunction(()=>mock.task.task_status==='Согласовано');assert.equal(await page.evaluate(()=>mock.requests[1].payload.layout_link),'https://files.example.org/layout.pdf');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.keyboard.press('Escape');await page.waitForSelector('[role=dialog]',{state:'detached'});assert.equal(await page.evaluate(()=>document.activeElement.id),'open');assert.deepEqual(errors,[]);results.push({width,emptyBlocked:true,unsafeBlocked:true,confirmationRequired:true,conflictKeepsInput:true,explicitLinkSent:true,overflow:false,focusReturned:true});await page.close()}await writeFile(path.join(out,'browser-report.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results))}finally{await browser.close();await new Promise(r=>server.close(r))}
