import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile,mkdir,writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),root=process.cwd(),output=path.join(root,'artifacts/client-registry');
const actor='90000000-0000-4000-8000-000000000502',id='90000000-0000-4000-8000-000000000503';
const mock=`
const client={id:'${id}',name:'Мастерская оформления фасадов и входных групп — длинное название клиента',phone:'+7 900 000 05 01',source:'Повторное обращение',comment:'Договориться о встрече',address:'Борисоглебск',updated_at:'2026-10-02T05:00:00Z'};
globalThis.mock={fail:false,lose:false,requests:[],receipts:new Map()};
export const supabaseClient={functions:{invoke:async(name,{body})=>{mock.requests.push(body);if(mock.fail)return {error:new Error('synthetic error')};if(body.action==='client.list')return {data:{ok:true,clients:[client],total:1}};if(body.action==='client.get')return {data:{ok:true,client,links:{leads:[],orders:[],lead_count:0,order_count:0},history:[]}};let result=mock.receipts.get(body.request_id);if(!result){Object.assign(client,body.payload);result={ok:true,client};mock.receipts.set(body.request_id,result);}if(mock.lose){mock.lose=false;return{error:new Error('response lost')}}return{data:result};}}};`;
const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Клиенты</title><link rel="stylesheet" href="/assets/brand/design-tokens.css"><link rel="stylesheet" href="/crm/v4/assets/v4/base.css"><style>body{margin:0;background:#f5f6f8;color:#172033;font-family:Arial,sans-serif}main{max-width:1240px;margin:auto;padding:16px;box-sizing:border-box}button,input,textarea{font:inherit;min-height:44px}button{padding:8px 12px;border:1px solid #b8c1ce;border-radius:6px;background:#fff;color:#172033}input,textarea{padding:9px;border:1px solid #b8c1ce;border-radius:6px;background:#fff;color:#172033}button.v4-primary{background:#bd1821;color:white}h1{font-size:24px}a{color:#9e111a}*:focus-visible{outline:3px solid #b51721;outline-offset:3px}</style></head><body data-v4-tab="clients"><main id="crmWorkspace"><h1>CRM Лидер</h1></main><script type="module">import{v4State}from'/crm/v4/assets/v4/state.js';v4State.user={id:'${actor}'};v4State.profileLoaded=true;v4State.profile={role:'manager',is_active:true};const m=await import('/crm/v4/assets/v4/client-registry-v1.js');await m.load();globalThis.ready=true;</script></body></html>`;
const server=createServer(async(req,res)=>{const p=new URL(req.url,'http://localhost').pathname;if(p==='/test'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(p.endsWith('/supabase-client.js')){res.setHeader('Content-Type','text/javascript');res.end(mock);return;}if(p.endsWith('/config.js')){res.setHeader('Content-Type','text/javascript');res.end("export const V4_CONFIG={supabaseUrl:'https://otulfnouybahfnsycxqn.supabase.co'};");return;}try{const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw 0;res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream');res.end(await readFile(f));}catch{res.statusCode=404;res.end('not found')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined});const results=[];
try{await mkdir(output,{recursive:true});for(const width of [360,390,768,1024,1440]){
 const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.waitForFunction(()=>globalThis.ready);
 await page.click('[data-client-open]');await page.click('[data-client-edit]');await page.fill('[name="comment"]','Комментарий после проверки');
 await page.addScriptTag({path:process.env.AXE_CORE_PATH||require.resolve('axe-core/axe.min.js')});const violations=await page.evaluate(async()=>(await axe.run(document.getElementById('clientRegistryV1'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})));
 assert.deepEqual(violations,[]);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 if(width===360||width===1440)await page.screenshot({path:path.join(output,`clients-${width}.png`),fullPage:true});
 await page.evaluate(()=>mock.lose=true);await page.click('#clientEditForm [type="submit"]');await page.waitForFunction(()=>document.querySelector('#clientSaveNotice').dataset.error==='true');assert.equal(await page.isDisabled('[name="comment"]'),true);
 await page.click('#clientEditForm [type="submit"]');await page.waitForSelector('[data-client-edit]');assert.match(await page.textContent('#clientDetail'),/Комментарий после проверки/);assert.equal(await page.evaluate(()=>mock.receipts.size),1);
 await page.click('[data-client-edit]');await page.keyboard.press('Escape');await page.waitForSelector('[data-client-edit]');
 await page.evaluate(async()=>{const{setState}=await import('/crm/v4/assets/v4/state.js');setState({profile:{role:'designer',is_active:true}});});assert.equal(await page.locator('#clientRegistryV1').count(),0,'role change must remove contact data');
 assert.deepEqual(errors,[]);results.push({width,overflow:false,violations,errors,responseLossReplay:true,roleChangeClearsData:true,escape:true});await page.close();
 }await writeFile(path.join(output,'browser-report.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));
}finally{await browser.close();await new Promise(r=>server.close(r));}
