import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),out=path.join(root,'artifacts/offer-card');
const mock=`
const offer={id:'offer-1',lead_id:'lead-1',calculation_id:'calc-1',title:'Вывеска для магазина',status:'Черновик',total_sum:1700,updated_at:'2026-10-02T12:00:00.123456Z',full_text:'Описание предложения',short_text:'Краткое предложение'};
const calc={id:'calc-1',lead_id:'lead-1',title:'Вывеска',client_total:1700};
globalThis.mock={offer,calc,delay:true,requests:[]};
export const supabaseClient={auth:{getSession:async()=>({data:{session:{user:{id:'actor-1'}}}})},functions:{invoke:async(name,{body})=>{mock.requests.push(body);offer.status=body.payload.status;offer.updated_at=new Date().toISOString();return{data:{ok:true,offer:{...offer},lead:{id:'lead-1',status:offer.status}}}}},from(table){const query={select(){return this},eq(){return this},order(){return this},limit(){return this},single(){return this},maybeSingle(){return this},async then(resolve){if(mock.delay&&table==='leader_commercial_offers'){mock.delay=false;await new Promise(r=>setTimeout(r,1300))}const data=table==='leader_commercial_offers'?{...offer}:table==='leader_lead_calculations'?calc:table==='leader_leads'?{id:'lead-1',name:'Клиент',status:'Новая'}:table==='leader_lead_calculation_items'?[{id:'item-1',name:'Вывеска',qty:1,client_sum:1700,client_price:1700}]:[];return resolve({data,error:null})}};return query}};
`;
const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Карточка КП</title><style>body{font:16px Arial;margin:0}button,input,select,textarea{font:inherit;min-height:44px;max-width:100%;box-sizing:border-box}button{padding:8px;background:white;border:1px solid #777;color:#172033;border-radius:6px}.v4-form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:10px}.v4-form-grid label{display:grid;gap:4px}.wide{grid-column:1/-1}*:focus-visible{outline:3px solid #b51721}</style></head><body><main><h1>Коммерческие предложения</h1><button id="open" data-open-offer-card="offer-1">Карточка КП</button></main><script type="module">import{v4State}from'/crm/v4/assets/v4/state.js';v4State.user={id:'actor-1'};v4State.profileLoaded=true;v4State.profile={role:'manager',is_active:true};await import('/crm/v4/assets/v4/offer-card-v1.js');globalThis.ready=true;</script></body></html>`;
const server=createServer(async(req,res)=>{const p=new URL(req.url,'http://localhost').pathname;res.setHeader('Content-Type','text/javascript');if(p==='/test'){res.setHeader('Content-Type','text/html');res.end(html);return}if(p.endsWith('/supabase-client.js')){res.end(mock);return}if(p.endsWith('/config.js')){res.end("export const V4_CONFIG={supabaseUrl:'https://otulfnouybahfnsycxqn.supabase.co'}");return}try{const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw 0;res.end(await readFile(f))}catch{res.statusCode=404;res.end('missing')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});const results=[];
try{await mkdir(out,{recursive:true});for(const width of [360,390,768,1024,1440]){const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.waitForFunction(()=>globalThis.ready);await page.click('#open');await page.click('[data-offer-transition="Отправлено"]');await page.click('[data-offer-transition="Согласовано"]');await page.waitForSelector('[data-create-order-from-offer]');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('#offerOrderCreateBox').count(),1);if(width===360||width===1440)await page.screenshot({path:path.join(out,`offer-${width}.png`),fullPage:true});await page.keyboard.press('Escape');await page.waitForSelector('[role=dialog]',{state:'detached'});assert.equal(await page.evaluate(()=>document.activeElement.id),'open');assert.deepEqual(errors,[]);results.push({width,delayedLoad:true,approvalShowsOrder:true,overflow:false,escape:true,errors});await page.close()}await writeFile(path.join(out,'browser-report.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results))}finally{await browser.close();await new Promise(r=>server.close(r))}
