import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';
import { financeAmount, financeDate, financeCreatePayload, fetchAllOrderFinance } from '../crm/v4/assets/v4/finance-record-model-v1.js';
import { financeWriteAvailable, prepareFinanceCommand, completeFinanceCommand, invokeFinanceCommand } from '../crm/v4/assets/v4/finance-record-transport-v1.js';
import { buildOrderFinanceSnapshot, firstFinanceNumber } from '../crm/v4/assets/v4/finance-plan-actual-model-v1.js';

assert.equal(financeAmount('1 000,25'), 1000.25);
for (const invalid of ['', 0, -1, '0.001', 'Infinity', 'NaN', '1e3', '1000000001', '1.2.3']) assert.throws(() => financeAmount(invalid));
assert.throws(() => financeDate('2026-02-30'));
assert.throws(() => financeDate('2099-01-01'));
assert.equal(financeDate('2026-02-28'), '2026-02-28');
assert.equal(firstFinanceNumber(0, 500), 0);
assert.equal(firstFinanceNumber(null, undefined, '', 'bad', 400), 400);
const payment = amount => ({ amount, payment_status: 'Проведён', payment_type: 'Приход', is_confirmed: true });
const snapshot = buildOrderFinanceSnapshot({ client_total: 1, contractor_cost: 0.4, profit: null }, [payment(0.1), payment(0.2)], [{ amount: 0.1, status: 'Проведён' }]);
assert.equal(snapshot.plannedProfit, 0.6);
assert.equal(snapshot.confirmedNetReceipts, 0.3);
assert.equal(snapshot.debt, 0.7);
assert.equal(snapshot.cashResult, 0.2);
assert.equal(buildOrderFinanceSnapshot({ client_total: 0, contractor_cost: 100, profit: 0 }).plannedProfit, 0);

let calls = 0;
const rows = Array.from({ length: 1234 }, (_, id) => ({ id }));
const query = { select() { return this; }, eq() { return this; }, order() { return this; }, async range(start, end) { calls++; return { data: rows.slice(start, end + 1) }; } };
assert.equal((await fetchAllOrderFinance({ from: () => query }, 'leader_payments', 'id', 'order')).length, 1234);
assert.equal(calls, 3);
query.range = async start => start ? { error: new Error('second_page_failed') } : { data: rows.slice(0, 500) };
await assert.rejects(fetchAllOrderFinance({ from: () => query }, 'leader_payments', 'id', 'order'), /second_page_failed/);

const stage = 'https://otulfnouybahfnsycxqn.supabase.co';
assert.equal(financeWriteAvailable(stage, true), true);
for (const url of ['https://ofewxuqfjhamgerwzull.supabase.co', stage + '.evil.test', 'http://otulfnouybahfnsycxqn.supabase.co']) assert.equal(financeWriteAvailable(url, true), false);
assert.equal(financeWriteAvailable(stage, false), false);
const actorId = '90000000-0000-4000-8000-000000000501';
const orderId = '90000000-0000-4000-8000-000000000502';
const values = new Map();
const storage = { getItem: key => values.get(key), setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key) };
const payload = financeCreatePayload({ orderId, kind: 'payment', amount: '1000,25', date: '2026-09-01', method: 'Перевод', category: 'Предоплата', comment: 'private comment' });
const input = { actorId, action: 'finance.payment.create', payload, expectedUpdatedAt: '2026-09-01T12:00:00.123Z', storage, cryptoObject: webcrypto };
const first = await prepareFinanceCommand(input);
const retry = await prepareFinanceCommand({ ...input, expectedUpdatedAt: '2026-09-02T12:00:00Z' });
assert.deepEqual(retry, first, 'timeout/reload must retain both request ID and original revision');
assert(!JSON.stringify([...values]).includes('private comment'));
assert(!JSON.stringify([...values]).includes('1000.25'));
const client = { auth: { getSession: async () => ({ data: { session: { access_token: 'synthetic-test' } } }) }, functions: { invoke: async () => new Promise(() => {}) } };
const timed = await invokeFinanceCommand({ client, url: stage, allowed: true, command: first.command, timeoutMs: 5 });
assert.equal(timed.uncertain, true);
assert.equal((await prepareFinanceCommand(input)).command.request_id, first.command.request_id);
client.functions.invoke = async () => ({ data: { ok: true, idempotent_replay: true } });
assert.equal((await invokeFinanceCommand({ client, url: stage, allowed: true, command: retry.command })).idempotent_replay, true);
completeFinanceCommand(first.key, storage);
assert.notEqual((await prepareFinanceCommand(input)).command.request_id, first.command.request_id);
client.functions.invoke = async () => ({ error: { context: new Response(JSON.stringify({ error: { code: 'source_changed' } }), { status: 409 }) } });
const rejected = await invokeFinanceCommand({ client, url: stage, allowed: true, command: retry.command });
assert.equal(rejected.uncertain, false);
assert.equal(rejected.code, 'source_changed');
assert.equal((await invokeFinanceCommand({ client, url: 'https://ofewxuqfjhamgerwzull.supabase.co', allowed: true, command: first.command })).code, 'production_locked');
console.log('Finance validation, complete pagination, cents, special prices and retry identity passed.');
