import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=process.cwd(),out=path.join(root,'artifacts/design-queue-actions');
const mock=`globalThis.mock={requests:[],conflict:false,task:{id:'11111111-1111-4111-8111-111111111111',order_id:'22222222-2222-4222-8222-222222222222',title:'Макет вывески',task_text:'Размер, материал, количество',task_status:'Новая',updated_at:'2026-10-03T10:00:00.123456Z'}};
export const supabaseClient={functions:{async invoke(slug,{body}){mock.requests.push({slug,body});await new Promise(r=>setTimeout(r,100));if(mock.conflict)return{error:{context:{clone:()=>({json:async()=>({error:{code:'conflict'}})})}}};mock.task.task_status=body.payload.status;mock.task.updated_at='2026-10-03T11:00:00.654321Z';if(body.payload.layout_link)mock.task.layout_link=body.payload.layout_link;return{data:{ok:true,task:{...mock.task}}}}},from(table){if(table==='leader_orders')throw new Error('Forbidden order read');return{select(){return this},order(){return this},limit(){return this},in(){return this},then(resolve){return resolve({data:table==='leader_design_tasks'?[{...mock.task}]:[],error:null})}}}};`;
const server=createServer(async(req,res)=>{const p=new URL(req.url,'http://localhost').pathname;res.setHeader('Content-Type','text/javascript');if(p==='/test'){res.setHeader('Content-Type','text/html');return res.end(`<!doctype html><html lang="ru"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;font:16px Arial}*:focus-visible{outline:3px solid #b51721}</style></head><body data-v4-tab="production"><main id="crmWorkspace"></main><script type="module">import{setState}from'/crm/v4/assets/v4/state.js';setState({user:{id:'designer'},profileLoaded:true,profile:{role:'designer',is_active:true}});const b=await import('/crm/v4/assets/v4/production-board-v3.js');b.mount();await b.load();document.getElementById('productionBoardSection').hidden=false;globalThis.ready=true;</script></body></html>`)}if(p.endsWith('/supabase-client.js'))return res.end(mock);if(p.endsWith('/config.js'))return res.end("export const V4_CONFIG={supabaseUrl:'https://ofewxuqfjhamgerwzull.supabase.co'}");try{const f=path.resolve(root,'.'+p);if(!f.startsWith(root+'/'))throw 0;res.end(await readFile(f))}catch{res.statusCode=404;res.end('missing')}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH});const results=[];
try{await mkdir(out,{recursive:true});for(const width of [360,390,768,1024,1440]){
 const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}/test`);await page.waitForFunction(()=>globalThis.ready);
 const form=page.locator('[data-design-queue-command]');await form.evaluate(f=>{f.requestSubmit();f.requestSubmit()});await page.waitForFunction(()=>mock.task.task_status==='В работе');assert.equal(await page.evaluate(()=>mock.requests.length),1);
 await page.click('[data-production-light-refresh]');await page.waitForSelector('[name=layout_link]');const link=page.locator('[name=layout_link]');await link.fill('https://user:pass@example.org/layout.pdf');await form.evaluate(f=>f.requestSubmit());assert.equal(await page.evaluate(()=>mock.requests.length),1);await link.fill('https://files.example.org/layout.pdf');await page.evaluate(()=>mock.conflict=true);await form.evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>document.querySelector('[data-design-queue-result]').textContent.includes('Задача изменилась'));assert.equal(await link.inputValue(),'https://files.example.org/layout.pdf');assert.equal(await form.locator('button').isEnabled(),true);await page.evaluate(()=>mock.conflict=false);await form.evaluate(f=>f.requestSubmit());await page.waitForFunction(()=>mock.task.task_status==='На согласовании');assert.equal(await page.evaluate(()=>mock.requests.at(-1).body.expected_updated_at),'2026-10-03T11:00:00.654321Z');assert.equal(await page.evaluate(()=>mock.requests.at(-1).slug),'leader-crm-design');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.evaluate(()=>document.activeElement.hasAttribute('data-design-queue-result')),true);if(width===360)await page.screenshot({path:path.join(out,'designer-360.png'),fullPage:true});assert.deepEqual(errors,[]);results.push({width,start:true,doubleSubmitGuard:true,safeLink:true,conflictKeepsInput:true,revisionPreserved:true,review:true,overflow:false,focus:true});await page.close();
}await writeFile(path.join(out,'browser-report.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));}finally{await browser.close();await new Promise(r=>server.close(r))}
