import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';
import { prepareClientCommand, completeClientCommand, invokeClientCommand } from '../crm/v4/assets/v4/client-registry-transport-v1.js';
import { canOpenV4Tab } from '../crm/v4/assets/v4/role-tab-permissions-v1.js';
import { v4State } from '../crm/v4/assets/v4/state.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const values=new Map(),storage={getItem:k=>values.get(k),setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
const actor='90000000-0000-4000-8000-000000000502',payload={name:'Synthetic',phone:'+7 900 000 05 01'};
const first=await prepareClientCommand(actor,'client.create',payload,undefined,storage);
const repeated=await prepareClientCommand(actor,'client.create',payload,undefined,storage);
assert.deepEqual(repeated,first);assert.equal([...values.values()].some(x=>x.includes('Synthetic')||x.includes('900 000')),false);
const revision='2026-10-02T05:00:00Z';
const update=await prepareClientCommand(actor,'client.update',{...payload,client_id:actor},revision,storage);
assert.equal((await prepareClientCommand(actor,'client.update',{...payload,client_id:actor},'2026-10-02T06:00:00Z',storage)).command.expected_updated_at,revision);
completeClientCommand(first.key,storage);assert.notEqual((await prepareClientCommand(actor,'client.create',payload,undefined,storage)).command.request_id,first.command.request_id);
const timeout=await invokeClientCommand({functions:{invoke:()=>new Promise(()=>{})}},'https://otulfnouybahfnsycxqn.supabase.co',first.command,5);assert.equal(timeout.uncertain,true);
v4State.profileLoaded=true;
for(const role of ['owner','admin','manager','accountant','designer','installer','contractor']) assert.equal(canOpenV4Tab('clients',{role,is_active:true}),['owner','admin','manager'].includes(role),role);
console.log('Client retry, privacy, uncertain result and UI permissions PASS.');
